%% plot figure 1

no_var = [1e-4, 10^(-3.5), 1e-3,10^(-2.5),1e-2,10^(-1.5), 1e-1, 10^(-0.5), 1, 10^0.5];
snr_db = zeros([length(no_var),1]);

for i = 1:length(no_var)
    snr_db(i) = 10 * log10(1/no_var(i));
end
semilogy(snr_db, dir_mse, 'o-',...
         'Color',[0.301 0.506 0.741],...
         'DisplayName',"ON/OFF: MSE of direct channel",...
         'LineWidth',1.5,...
         'MarkerSize',6);
hold on;
     
semilogy(snr_db, cas_mse, 's-',...
         'Color',[0.608 0.733 0.35],...
         'DisplayName',"ON/OFF: MSE of cascaded channel",...
         'LineWidth',1.5,...
         'MarkerSize',6);
hold on;
semilogy(snr_db, dir_mse_dft, 'o-',...
         'Color',[0.75 0.31 0.27],...
         'DisplayName',"DFT: MSE of direct channel",...
         'LineWidth',1.5,...
         'MarkerSize',6);
hold on;
semilogy(snr_db, cas_mse_dft, 's-',...
         'Color',1/255 *[238 176 30],...
         'DisplayName',"DFT: MSE of cascaded channel",...
         'LineWidth',1.5,...
         'MarkerSize',6);

grid on;
xlabel("SNR (dB)");
ylabel("Mean squared error"); % averaged over all the channel coefficients

%%
semilogy(snr_db, dir_mse, 'o-',...
         'Color',[0.301 0.506 0.741],...
         'DisplayName',"ON/OFF: MSE of direct channel",...
         'LineWidth',1.5,...
         'MarkerSize',6);
     
hold on;
semilogy(snr_db, dir_mse_dft, 'o-',...
         'Color',[0.75 0.31 0.27],...
         'DisplayName',"DFT: MSE of direct channel",...
         'LineWidth',1.5,...
         'MarkerSize',6);
     
     grid on;
xlim([-5,40]);
xlabel("SNR (dB)");
ylabel("Mean squared error"); % averaged over all the channel coefficients

%%

     
semilogy(snr_db, cas_mse, 's-',...
         'Color',[0.608 0.733 0.35],...
         'DisplayName',"ON/OFF: MSE of cascaded channel",...
         'LineWidth',1.5,...
         'MarkerSize',6);
hold on;
semilogy(snr_db, cas_mse_dft, 's-',...
         'Color',1/255 *[238 176 30],...
         'DisplayName',"DFT: MSE of cascaded channel",...
         'LineWidth',1.5,...
         'MarkerSize',6);

grid on;
xlim([-5,40]);
xlabel("SNR (dB)");
ylabel("Mean squared error"); % averaged over all the channel coefficients

%%

K_set = [20,40,60,80,100];

semilogy(K_set, dir_mse, 'o-',...
         'Color',[0.301 0.506 0.741],...
         'DisplayName',"ON/OFF: MSE of direct channel",...
         'LineWidth',1.5,...
         'MarkerSize',6);
hold on;
     
semilogy(K_set, cas_mse, 's-',...
         'Color',[0.608 0.733 0.35],...
         'DisplayName',"ON/OFF: MSE of cascaded channel",...
         'LineWidth',1.5,...
         'MarkerSize',6);
hold on;
semilogy(K_set, dir_mse_dft, 'o-',...
         'Color',[0.75 0.31 0.27],...
         'DisplayName',"DFT: MSE of direct channel",...
         'LineWidth',1.5,...
         'MarkerSize',6);
hold on;
semilogy(K_set, cas_mse_dft, 's-',...
         'Color',1/255 *[238 176 30],...
         'DisplayName',"DFT: MSE of cascaded channel",...
         'LineWidth',1.5,...
         'MarkerSize',6);

grid on;
grid on;
xlabel("The number of IRS elements K");
ylabel("Mean squared error"); % averaged over all the channel coefficients
ylim([1e-4 1e-1]);

%%
T_set = [51:10:101];

figure;

semilogy(T_set, dir_mse_dft, 'o-',...
         'Color',[0.301 0.506 0.741],...
         'DisplayName',"DFT: MSE of direct channel",...
         'LineWidth',1.5,...
         'MarkerSize',6);
hold on;

semilogy(T_set, cas_mse_dft, 's-',...
         'Color',[0.608 0.733 0.35],...
         'DisplayName',"DFT: MSE of cascaded channel",...
         'LineWidth',1.5,...
         'MarkerSize',6);

grid on;
xlabel("The length of pilot sequence T");
ylabel("Mean squared error"); % averaged over all the channel coefficients